# @package _global_

### Environment Configuration ###
cauldron:
  randomize: false
  cauldron_index: 10 # Storm_Cauldron_2
recipe:
  randomize: false
ingredients:
  randomize: false
  allowed_ingredients: null
