# @package _global_

### Environment Configuration ###
cauldron:
  randomize: false
  cauldron_index: 37 # Magical_Wasteland_Cauldron_2
recipe:
  randomize: false
ingredients:
  randomize: false
  allowed_ingredients: null
