# @package _global_

### Environment Configuration ###
cauldron:
  randomize: false
  cauldron_index: 2 # Mudpack_Cauldron_0
recipe:
  randomize: false
ingredients:
  randomize: false
  allowed_ingredients: null
