defaults:
  - _self_
  - reward: default


data:
  potionomics_cauldrons: data/potionomics_cauldrons.csv
  potionomics_ingredients: data/potionomics_ingredients.csv
  potionomics_recipes: data/potionomics_recipes.csv

# Configurations of the environment that may change per episode
cauldron:
  randomize: true
  cauldron_index: 0

recipe:
  randomize: true
  recipe_index: 0

ingredients:
  randomize: true
  minimum_amount: 0
  maximum_amount: 10
  allowed_ingredients: null
