data:
  potionomics_cauldrons: data/potionomics_cauldrons.csv
  potionomics_ingredients: data/potionomics_ingredients.csv
  potionomics_recipes: data/potionomics_recipes.csv

# Configurations of the environment that may change per episode
episode_cfg:
  randomize_cauldron: false
  randomize_recipe: false
  randomize_ingredient_amount: false
  # Index of the cauldron to use by default if randomize_cauldron is false
  default_cauldron_index: 0
  # Index of the recipe to use by default if randomize_recipe is false
  default_recipe_index: 0
  # The default amount of each ingredient available by default if randomize_ingredient_amount is false
  default_ingredient_amount: 10  


reward_cfg:
  illegal_move_reward: -1.0
  insufficient_items_in_cauldron_reward: -1.0
  stability_reward:
    - -1.0
    - 0.0
    - 0.5
    - 0.8
    - 1.0